13:24:11 File：c:\users\李旻恩\desktop\0504\抓錯誤.py,Line：24,Detail：list index out of range
